### ISSUE TITLE
CSS-Skill

### ISSUE THREAD

**Issue by alekoshen712** [alekoshen712/Blog#3]
1. 多用 :not() 伪类选择器
```css
/*not*/
.nav li:last-child {
  border-right: none;
}
/*better*/
.nav li:not(:last-child) {
  border-right: 1px solid #666;
}
```
2. 不知道怎么叫,反正经常用
```css
/* 效果就是这样 a,b,c */
span:not(:last-child)::after {
  content: ",";
}
```
3. 使用负的 nth-child 来选择元素
```css
/* 前三个元素背景为red */
li:nth-child(-n+3) {
  background: red;
}
```
4. 使用 height + overflow 来做滑块
```css
.slider {
  height: 100px;
  transition: 0.3s;
  overflow: hidden;
}
.slider:hover {
  height: 600px;
}
```
